# MongoDB Configuration

production_master_side:
  clients:
    default: # master (writable)
      database: ss
      hosts:
        - localhost:27017
    default_post:
      database: ss_post
      hosts:
        - localhost:27018
    # slave side (public, public_2, public_3,,)
    public:
      database: ss_post
      hosts:
        - otherhost:27018

production_slave_side:
  clients:
    default: # slave (readonly)
      database: ss
      hosts:
        - localhost:27017
    default_post: # (writable)
      database: ss_post
      hosts:
        - localhost:27018
